lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v1.2.4@sha256:c71b10b6810c736d22f32f370ec80805fd58df053cdfc84a938fa1f47b4dbeda
  debug: false
  localK8sAPIEndpoint:
    enabled: true
  # nodeSelector for the DaemonSet
  # Talos uses empty value: "node-role.kubernetes.io/control-plane": ""
  # Generic k8s (k3s, kubeadm) uses: "node-role.kubernetes.io/control-plane": "true"
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
