backupController:
  image: "ghcr.io/cozystack/cozystack/backup-controller:v1.1.7@sha256:2d7ba777aa2fcad377117e3691f0943b0d04db9351f67cda846fa9bc59b813cc"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
