backupController:
  image: "ghcr.io/cozystack/cozystack/backup-controller:v1.2.4@sha256:52c8cda293e8a8acdc6adf0caf5d3a583fe696c4ffb14425f4012fc7a6ffb267"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
