kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.2.4@sha256:7febb6fc3c2fa0635c91844a73434b0a0637fbac0840e3d16533d347467e87fa
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.2.4@sha256:7febb6fc3c2fa0635c91844a73434b0a0637fbac0840e3d16533d347467e87fa
