kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.1.7@sha256:d8677f6f6fe06e7bb6c713ad5af9e21340d125c1a4e7ef5ef7003cb9c5807918
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.1.7@sha256:d8677f6f6fe06e7bb6c713ad5af9e21340d125c1a4e7ef5ef7003cb9c5807918
