backupStrategyController:
  image: "ghcr.io/cozystack/cozystack/backupstrategy-controller:v1.2.4@sha256:f5bc3fea186bc2fb886b0a54fe5dd585c22ca6f11cebb03751a3f115302950f0"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
